cuDNN present
Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]Fetching 3 files:  33%|███▎      | 1/3 [00:43<01:27, 43.78s/it]Fetching 3 files: 100%|██████████| 3/3 [00:47<00:00, 12.59s/it]Fetching 3 files: 100%|██████████| 3/3 [00:47<00:00, 15.71s/it]
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:  33%|███▎      | 1/3 [00:05<00:10,  5.48s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [00:10<00:05,  5.40s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:15<00:00,  5.11s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:15<00:00,  5.20s/it]
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:  33%|███▎      | 1/3 [00:01<00:03,  1.69s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [00:03<00:01,  1.67s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:04<00:00,  1.60s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:04<00:00,  1.62s/it]
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfs/home5/ahaldar/projects/llm-orchestrator/src/main.py", line 170, in <module>
    main()
  File "/gpfs/home5/ahaldar/projects/llm-orchestrator/src/main.py", line 152, in main
    result = run_controller(task_text, agent_a, agent_b, max_rounds=strategy.max_rounds, kind=kind)
NameError: name 'run_controller' is not defined
srun: error: gcn156: task 0: Exited with exit code 1
srun: Terminating StepId=15295841.0
