cuDNN present
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.9/runpy.py", line 158, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/gpfs/home5/ahaldar/projects/llm-orchestrator/src/main.py", line 2
    from __future__ import annotations
    ^
SyntaxError: from __future__ imports must occur at the beginning of the file
srun: error: gcn101: task 0: Exited with exit code 1
srun: Terminating StepId=15296441.0
